apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "silo.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "silo.name" . }}
    helm.sh/chart: {{ include "silo.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "silo.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "silo.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}          
          env:
            - name: "dbconnection"
              valueFrom:
                secretKeyRef: 
                  name: dbconnections
                  key: dbconnection
            - name: "ClusterId"
              value: aks
            - name: "MudLibPath"
              value: "/app/game.mudlib/"
          ports:
            - name: siloport
              containerPort: 11111
              protocol: TCP
            - name: gatewayport
              containerPort: 30000
              protocol: TCP   
   
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      imagePullSecrets:
            - name: wingms-key  
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
