apiVersion: v1
kind: Service
metadata:
  name: {{ include "silo.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "silo.name" . }}
    helm.sh/chart: {{ include "silo.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 11111
      targetPort: 11111
      protocol: TCP
      name: 'siloport'
    - port: 30000
      targetPort: 30000
      protocol: TCP
      name: 'gatewayport'
  selector:
    app.kubernetes.io/name: {{ include "silo.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
